### ISSUE TITLE
Dependencies lock file is missing

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-calendar#1]
Upstream issue: https://github.com/ProtonMail/WebClient/issues/158

**Comment by dhoko** [comment]
We will add a lock once we start to tag this app. (we could for the beta :thinking: )

**Comment by vladimiry** [comment]
Yeah but I just placed the issue for tracking purposes.

**Comment by vladimiry** [comment]
Closed by 5ec480f0b0033264e3d423c75f5f550df151fc91.
