### ISSUE TITLE
Cannot login password must not be longer than 71 bytes

### ISSUE THREAD

**Issue by BeatRoy** [ProtonMail/proton-calendar#12]
On the android app when I try to login it gives me the error:
My password is 100 characters long and every other proton app has no problems with it

![photo_2021-04-19_00-12-45](https://user-images.githubusercontent.com/26458713/115162487-4a2c8380-a093-11eb-8f28-276d78d06bb6.jpg)

I am running on:
Samsung S20+ 5G
Android 11
ProtonCalendar: 0.19.0

**Comment by valentinbonneaud** [comment]
Thanks for your report @BeatRoy. We identified the issue on our end, a fix is coming very soon. Sorry for the inconvenience.

**Comment by BeatRoy** [comment]
@valentinbonneaud Thanks next time I will try doing it trough the options you have provided

**Comment by valentinbonneaud** [comment]
@BeatRoy we fixed this issue on our side. Could you confirm that it is fixed on your side?

**Comment by BeatRoy** [comment]
@valentinbonneaud Yes it works now!! Thanks for fixing the bug
