### ISSUE TITLE
Feature request : ICS Format support

### ISSUE THREAD

**Issue by SimonVanacco** [ProtonMail/proton-calendar#13]
Hi !

I often get .ics files by email, and like to open them and import them directly from my phone. 
Proton Calendar cannot currently open them to import.

Is there any way that this feature could be present on a future version ? 
Current version : Calendar 0.19.1 on Android 10

Thanks a lot for this awesome beta :)

**Comment by valentinbonneaud** [comment]
Hi @SimonVanacco! Thanks for your feedback, the ICS import/parsing on the Android app is planned on our side. It will be released in the coming months.

I'm closing your feature request as this repository is dedicated to the Web client.
