### ISSUE TITLE
Feature Request: Widget for Android

### ISSUE THREAD

**Issue by GaryPWhite** [ProtonMail/proton-calendar#18]
Hey there Proton Calendar folks!

I'm a new proton person and noticed that the calendar app is around. I use gcal right now (work uses google suite) and like having a widget on my home screen to show the month's / day's events. Is a widget something y'all have been considering?

**Comment by econdepe** [comment]
Hey Gary, nice to see new ProtonCalendar users :tada: , but this repo is only for the web app ;). I believe the mobile app teams are indeed considering to implement a homescreen widget, but nothing concrete for the moment. When they go open-source, I guess you can ask them directly in the corresponding github repo. In the meantime I'll close this one
