### ISSUE TITLE
[proton-pack] Module not found: Error

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-calendar#2]
> [proton-pack] Module not found: Error: Can't resolve 'core-js/modules/es.symbol.description'

> [proton-pack] Module not found: Error: Can't resolve 'react-components/containers/app/StandardPreload'

There would probably be no such issue if #1 was resolved.

**Comment by dhoko** [comment]
Voilà, sync done, `npm ci` works ;)

**Comment by vladimiry** [comment]
Very nice. I can see that it's not just `package-lock.json` got added but also new changes landed into the branch. So I'm going to try the updates today later.
