### ISSUE TITLE
Documentation cleanup and updates.

### ISSUE THREAD

**Issue by gohanko** [ProtonMail/proton-calendar#3]
I noticed that on a few of ProtonMail's repositories, the documentation is a bit lacking and has some minor issues such as

- Spelling errors.
- Missing documentation on some of the npm commands and what they do.
- Weirdly formatted items (such as using quotes for notices/notes).

This seems to be minor stuff but does it need fixing? I think with some work, it is possible to reduce the size of the documentation and improve readability / understandability when reading at first glance.

Please let me know what you think, I can make a PR for this.

@mmso @EpokK @nico3333fr (Sorry if I ping too many, I'm not sure who to alert)

**Comment by Nolski** [comment]
Also subscribing here, are protonmail github issues maintained? Is this the place to report new issues & are outside contributions accepted?

**Comment by gohanko** [comment]
@Nolski I don't think they are, I'll be closing this.

**Comment by dhoko** [comment]
:wave: 

Sorry we didn't give you an answer, there is an issue about it, its WIP. A fix will be available soon.
But yeah a PR is always possible ;) 

The current Readme is obsolete :grin: that's an issue yes.

**Comment by dhoko** [comment]
@gohanko @Nolski we updated the readme https://github.com/ProtonMail/proton-calendar/blob/master/README.md

**Comment by gohanko** [comment]
@dhoko Cool
