### ISSUE TITLE
Is it possible to integrate Proton Calendar into another app using OAuth?

### ISSUE THREAD

**Issue by Borumer** [ProtonMail/proton-calendar#5]
I am developing an app and I would like to have users integrate a calendar into the mobile app (as it is a productivity app). Is it possible to integrate Proton Calendar using an API and a token? Does ProtonMail plan on making this possible in the feature?

**Comment by valentinbonneaud** [comment]
At the moment, Proton's API is not open to third-party applications but we’ll consider this suggestion. Thanks for your comment!

**Comment by Borumer** [comment]
@valentinbonneaud Thank you! Should I close this issue?

**Comment by valentinbonneaud** [comment]
Yes, you can! Thanks!
